name: flower_cnn_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy
  - matplotlib
  - scikit-learn
  - opencv
  - pillow
  - scipy
  - pytorch
  - torchvision
  - torchaudio
  - tqdm
  - pip
  - pip:
    - requests